"""
Internal hiring profiles knowledge base for ResumeLens AI.
Defines required skills, preferred skills, nice-to-have skills, expected projects,
experience levels, and key technologies for 24+ industry roles.
"""

from typing import Dict, List, Any

ROLES_DATABASE: Dict[str, Dict[str, Any]] = {
    "Software Engineer": {
        "title": "Software Engineer",
        "category": "Core Engineering",
        "required_skills": ["Data Structures & Algorithms", "Java", "Python", "OOP", "DBMS", "Operating Systems", "SQL", "REST APIs", "Git"],
        "preferred_skills": ["Docker", "AWS", "CI/CD", "System Design", "Unit Testing", "Redis", "Kafka"],
        "nice_to_have": ["Kubernetes", "GraphQL", "Microservices", "Terraform"],
        "expected_projects": ["Distributed Key-Value Store", "E-Commerce Microservices Platform", "Real-Time Chat Application", "REST API Backend with Rate Limiting"],
        "expected_experience_level": "1-3 Years",
        "expected_technologies": ["Java", "Python", "PostgreSQL", "Docker", "Git", "Spring Boot", "FastAPI"],
        "ats_keywords": ["algorithms", "object-oriented programming", "database design", "restful api", "git", "version control", "unit testing", "system architecture"],
    },
    "Frontend Developer": {
        "title": "Frontend Developer",
        "category": "Web & UI",
        "required_skills": ["React", "JavaScript (ES6+)", "TypeScript", "HTML5", "CSS3", "Tailwind CSS", "REST APIs", "Git", "State Management (Redux/Zustand)"],
        "preferred_skills": ["Next.js", "SSR/SSG", "Web Performance Optimization", "Accessibility (WCAG)", "Jest/RTL", "Cypress"],
        "nice_to_have": ["GraphQL", "Three.js", "WebSockets", "PWA"],
        "expected_projects": ["Design System Component Library", "Interactive Analytics Dashboard", "SaaS Landing Page with Micro-interactions", "E-Commerce UI with Cart & Checkout"],
        "expected_experience_level": "1-3 Years",
        "expected_technologies": ["React", "Next.js", "TypeScript", "Tailwind CSS", "Webpack", "Vite", "Framer Motion"],
        "ats_keywords": ["react.js", "typescript", "frontend architecture", "responsive design", "web performance", "dom manipulation", "state management", "cross-browser compatibility"],
    },
    "Backend Developer": {
        "title": "Backend Developer",
        "category": "Core Engineering",
        "required_skills": ["Python / Java / Node.js", "SQL & Database Design", "RESTful APIs", "ORM", "Git", "Authentication & Authorization (JWT/OAuth)", "Data Structures"],
        "preferred_skills": ["Docker", "Redis Caching", "Message Queues (RabbitMQ/Kafka)", "System Design", "Microservices", "PostgreSQL"],
        "nice_to_have": ["Kubernetes", "gRPC", "Elasticsearch", "AWS SQS/SNS"],
        "expected_projects": ["High-Throughput API Gateway", "Asynchronous Task Processing Worker", "Distributed File Upload Service", "Event-Driven Billing Pipeline"],
        "expected_experience_level": "2-4 Years",
        "expected_technologies": ["Node.js", "Express", "Python", "FastAPI", "Java", "Spring Boot", "PostgreSQL", "Redis", "Docker"],
        "ats_keywords": ["backend development", "api development", "database optimization", "microservices", "sql", "caching", "scalability", "concurrency"],
    },
    "Full Stack Developer": {
        "title": "Full Stack Developer",
        "category": "Web & UI",
        "required_skills": ["React / Next.js", "Node.js / Express / FastAPI", "TypeScript", "SQL / MongoDB", "REST APIs", "Git", "HTML/CSS"],
        "preferred_skills": ["Docker", "AWS / Vercel", "Tailwind CSS", "Redis", "CI/CD", "Testing (Jest/PyTest)"],
        "nice_to_have": ["GraphQL", "WebSockets", "Microservices", "Prisma / Drizzle"],
        "expected_projects": ["Full-Stack SaaS Application with Payments", "Real-Time Collaboration Workspace", "Job Application Tracking System", "Content Management System"],
        "expected_experience_level": "2-4 Years",
        "expected_technologies": ["React", "Next.js", "Node.js", "TypeScript", "PostgreSQL", "Tailwind CSS", "Docker", "Git"],
        "ats_keywords": ["full stack", "frontend", "backend", "web development", "typescript", "database", "api integration", "cloud deployment"],
    },
    "Java Developer": {
        "title": "Java Developer",
        "category": "Enterprise",
        "required_skills": ["Java 17+", "Spring Boot", "Spring Data JPA / Hibernate", "REST APIs", "SQL", "Maven / Gradle", "OOP & Design Patterns", "Git"],
        "preferred_skills": ["Microservices Architecture", "Docker", "Kafka", "JUnit / Mockito", "Redis", "Spring Security"],
        "nice_to_have": ["Kubernetes", "AWS", "gRPC", "Reactive Java (Project Reactor)"],
        "expected_projects": ["Spring Boot Microservices E-Commerce System", "Banking Transaction Processing Engine", "JWT Authenticated RBAC API", "Event-Driven Inventory Tracker"],
        "expected_experience_level": "2-5 Years",
        "expected_technologies": ["Java", "Spring Boot", "Hibernate", "PostgreSQL", "MySQL", "Docker", "Kafka", "Maven"],
        "ats_keywords": ["java", "spring boot", "jpa", "hibernate", "enterprise applications", "object-oriented programming", "microservices", "maven"],
    },
    "Python Developer": {
        "title": "Python Developer",
        "category": "Core Engineering",
        "required_skills": ["Python 3.10+", "FastAPI / Django / Flask", "PostgreSQL / MySQL", "REST APIs", "Git", "Data Structures", "Asyncio"],
        "preferred_skills": ["Docker", "Celery / Redis", "PyTest", "SQLAlchemy", "Pandas", "CI/CD"],
        "nice_to_have": ["AWS", "GraphQL", "Web Scraping (Playwright/Scrapy)", "Kubernetes"],
        "expected_projects": ["FastAPI Asynchronous Data Pipeline", "Django SaaS Backend with Payments", "Automated Web Scraping Engine", "REST API with Celery Task Queue"],
        "expected_experience_level": "1-3 Years",
        "expected_technologies": ["Python", "FastAPI", "Django", "PostgreSQL", "Redis", "Docker", "Celery", "PyTest"],
        "ats_keywords": ["python", "django", "fastapi", "rest api", "asynchronous programming", "orm", "pytest", "sql"],
    },
    "AI Engineer": {
        "title": "AI Engineer",
        "category": "AI & Data",
        "required_skills": ["Python", "PyTorch / TensorFlow", "LLMs & Prompt Engineering", "Vector Databases (Chroma/Qdrant/Pinecone)", "RAG Architecture", "LangChain / LlamaIndex", "REST APIs", "Git"],
        "preferred_skills": ["MLOps", "Docker", "HuggingFace Transformers", "Fine-Tuning (LoRA)", "FastAPI", "GPU Acceleration (CUDA)"],
        "nice_to_have": ["vLLM / Ollama", "DeepSpeed", "LangGraph", "Semantic Search"],
        "expected_projects": ["Multimodal RAG Knowledge Base Engine", "Autonomous LLM Agent Swarm", "Fine-Tuned Domain-Specific LLM Assistant", "Real-Time AI Document Parser"],
        "expected_experience_level": "2-4 Years",
        "expected_technologies": ["Python", "PyTorch", "HuggingFace", "LangChain", "FastAPI", "ChromaDB", "Docker", "OpenAI / Gemini API"],
        "ats_keywords": ["artificial intelligence", "large language models", "rag", "vector database", "prompt engineering", "langchain", "pytorch", "deep learning"],
    },
    "Machine Learning Engineer": {
        "title": "Machine Learning Engineer",
        "category": "AI & Data",
        "required_skills": ["Python", "Scikit-Learn", "PyTorch / TensorFlow", "Pandas & NumPy", "Feature Engineering", "Model Evaluation & Validation", "SQL", "Git"],
        "preferred_skills": ["MLflow / Weights & Biases", "MLOps Pipelines", "Docker", "Kubeflow / Airflow", "FastAPI / Model Serving", "XGBoost / LightGBM"],
        "nice_to_have": ["ONNX Runtime", "TRT", "Spark / Distributed Training", "Computer Vision / NLP"],
        "expected_projects": ["End-to-End Predictive Maintenance Pipeline", "Customer Churn Prediction & Model API", "Computer Vision Object Detection System", "Recommendation Engine with Matrix Factorization"],
        "expected_experience_level": "2-4 Years",
        "expected_technologies": ["Python", "PyTorch", "Scikit-Learn", "Pandas", "MLflow", "FastAPI", "Docker", "PostgreSQL"],
        "ats_keywords": ["machine learning", "supervised learning", "model deployment", "feature engineering", "mlops", "pytorch", "scikit-learn", "data science"],
    },
    "Data Scientist": {
        "title": "Data Scientist",
        "category": "AI & Data",
        "required_skills": ["Python / R", "SQL & Complex Queries", "Statistical Analysis & Hypothesis Testing", "Pandas / NumPy / SciPy", "Data Visualization (Matplotlib/Seaborn)", "Machine Learning (Scikit-Learn)", "Git"],
        "preferred_skills": ["Tableau / PowerBI", "A/B Testing Methodology", "XGBoost", "BigQuery / Snowflake", "PySpark"],
        "nice_to_have": ["Deep Learning", "NLP", "Time Series Forecasting (Prophet/Arima)", "Streamlit / Dash"],
        "expected_projects": ["Customer Lifetime Value Segmentation Model", "E-Commerce A/B Test Impact Analysis", "Financial Risk Time-Series Forecasting", "Automated EDA & Reporting Tool"],
        "expected_experience_level": "2-4 Years",
        "expected_technologies": ["Python", "SQL", "Pandas", "Scikit-Learn", "Matplotlib", "Jupyter", "Tableau", "Snowflake"],
        "ats_keywords": ["data science", "statistical modeling", "sql", "exploratory data analysis", "hypothesis testing", "predictive modeling", "business intelligence", "a/b testing"],
    },
    "DevOps Engineer": {
        "title": "DevOps Engineer",
        "category": "Infrastructure",
        "required_skills": ["Linux System Administration", "Docker", "Kubernetes", "CI/CD (GitHub Actions / GitLab CI / Jenkins)", "Terraform / Infrastructure as Code", "Bash / Python Scripting", "Git"],
        "preferred_skills": ["AWS / GCP / Azure", "Prometheus & Grafana Monitoring", "Ansible", "Helm", "Nginx / Reverse Proxies"],
        "nice_to_have": ["ArgoCD / GitOps", "Service Mesh (Istio)", "Security Scanning (Trivy)", "Elastic Stack (ELK)"],
        "expected_projects": ["Zero-Downtime Kubernetes Deployment Pipeline", "Multi-Region Cloud Infrastructure with Terraform", "Automated CI/CD Pipeline for Microservices", "Centralized Observability & Alerting Stack"],
        "expected_experience_level": "2-5 Years",
        "expected_technologies": ["Docker", "Kubernetes", "Terraform", "AWS", "GitHub Actions", "Prometheus", "Grafana", "Linux"],
        "ats_keywords": ["devops", "kubernetes", "docker", "ci/cd", "terraform", "cloud infrastructure", "linux", "monitoring", "automation"],
    },
    "Cloud Engineer": {
        "title": "Cloud Engineer",
        "category": "Infrastructure",
        "required_skills": ["AWS / GCP / Azure Architecture", "IAM & Cloud Security", "Networking (VPC, Subnets, Security Groups, Route53)", "Terraform / CloudFormation", "Docker", "Python / Bash", "Git"],
        "preferred_skills": ["Serverless (Lambda / Cloud Functions)", "Kubernetes (EKS / GKE)", "Cloud Monitoring (CloudWatch / Stackdriver)", "Cost Optimization"],
        "nice_to_have": ["AWS Certified Solutions Architect", "FinOps", "Multi-Cloud Strategy", "Site Reliability Engineering (SRE)"],
        "expected_projects": ["High-Availability AWS VPC Architecture", "Serverless Data Processing Pipeline", "Cloud Migration Strategy & Implementation", "Automated Compliance & Security Scanner"],
        "expected_experience_level": "2-5 Years",
        "expected_technologies": ["AWS", "Terraform", "Docker", "Python", "Linux", "Kubernetes", "CloudWatch", "Serverless"],
        "ats_keywords": ["cloud engineer", "aws", "terraform", "cloud architecture", "vpc", "iam", "serverless", "infrastructure as code"],
    },
    "Cyber Security Engineer": {
        "title": "Cyber Security Engineer",
        "category": "Infrastructure",
        "required_skills": ["Network Security & Protocols", "Penetration Testing / Ethical Hacking", "Vulnerability Assessment & OWASP Top 10", "Linux & Windows Security", "Python / Bash Scripting", "SIEM Tools (Splunk / Elastic Security)", "Git"],
        "preferred_skills": ["Cryptography & PKI", "Incident Response", "Identity & Access Management (IAM)", "Docker Security", "Cloud Security (AWS GuardDuty)"],
        "nice_to_have": ["CEH / CISSP / OSCP Certifications", "Reverse Engineering (Ghidra/Wireshark)", "Zero Trust Architecture"],
        "expected_projects": ["Automated OWASP Web Application Vulnerability Scanner", "Network Intrusion Detection System (NIDS)", "SIEM Security Log Aggregator & Alerting Engine", "Hardened Docker Base Image Pipeline"],
        "expected_experience_level": "2-5 Years",
        "expected_technologies": ["Linux", "Python", "Wireshark", "Burp Suite", "Splunk", "Nmap", "Metasploit", "Docker"],
        "ats_keywords": ["cyber security", "penetration testing", "vulnerability assessment", "owasp", "network security", "siem", "incident response", "cryptography"],
    },
    "Android Developer": {
        "title": "Android Developer",
        "category": "Mobile",
        "required_skills": ["Kotlin", "Android SDK", "Jetpack Compose / XML Layouts", "MVVM / Clean Architecture", "Coroutines & Flow", "Retrofit & REST APIs", "Room DB", "Git"],
        "preferred_skills": ["Dagger / Hilt Dependency Injection", "Unit Testing (JUnit / Espresso)", "CI/CD for Android (Fastlane)", "Google Play Deployment"],
        "nice_to_have": ["KMP (Kotlin Multiplatform)", "Android NDK / C++", "WorkManager", "Firebase Services"],
        "expected_projects": ["Native Jetpack Compose Fitness Tracker", "Offline-First News Reader with Room & Coroutines", "E-Commerce App with Payment Integration", "Real-Time Chat App with WebSockets"],
        "expected_experience_level": "2-4 Years",
        "expected_technologies": ["Kotlin", "Android SDK", "Jetpack Compose", "Retrofit", "Room", "Hilt", "Git"],
        "ats_keywords": ["android developer", "kotlin", "jetpack compose", "mvvm", "android sdk", "coroutines", "retrofit", "mobile app development"],
    },
    "iOS Developer": {
        "title": "iOS Developer",
        "category": "Mobile",
        "required_skills": ["Swift", "iOS SDK", "SwiftUI / UIKit", "MVVM Architecture", "Combine / Async-Await", "CoreData / SwiftData", "REST API Integration (URLSession)", "Git"],
        "preferred_skills": ["Dependency Injection", "Unit & UI Testing (XCTest)", "CI/CD (Fastlane / Xcode Cloud)", "App Store Publishing Guidelines"],
        "nice_to_have": ["CoreML", "ARKit", "WatchOS / WidgetKit", "Objective-C Interop"],
        "expected_projects": ["Native SwiftUI Social Media App", "Offline-First Task Management App with SwiftData", "Audio Player with Background Audio & Lockscreen Controls", "Fintech Dashboard with Interactive Charts"],
        "expected_experience_level": "2-4 Years",
        "expected_technologies": ["Swift", "SwiftUI", "UIKit", "Xcode", "CoreData", "Combine", "Git"],
        "ats_keywords": ["ios developer", "swift", "swiftui", "uikit", "ios sdk", "combine", "xcode", "mobile application"],
    },
    "QA Engineer": {
        "title": "QA Engineer",
        "category": "Quality & Testing",
        "required_skills": ["Software Testing Life Cycle (STLC)", "Test Case Design & Execution", "Manual Testing Techniques", "Bug Tracking (Jira)", "API Testing (Postman / Insomnia)", "SQL Queries", "Git"],
        "preferred_skills": ["Automation Testing (Selenium / Cypress / Playwright)", "Python / JavaScript", "Regression & Smoke Testing", "CI/CD Integration"],
        "nice_to_have": ["Performance Testing (JMeter)", "Security Testing Basics", "Mobile Testing (Appium)"],
        "expected_projects": ["Comprehensive Test Plan & Suite for SaaS Platform", "Automated Web E2E Test Suite in Cypress/Playwright", "API Automation Framework with Postman & Newman", "Cross-Browser Compatibility Matrix"],
        "expected_experience_level": "1-3 Years",
        "expected_technologies": ["Jira", "Postman", "Selenium", "Cypress", "Python", "SQL", "Git"],
        "ats_keywords": ["qa engineer", "quality assurance", "test cases", "manual testing", "bug tracking", "stlc", "api testing", "jira"],
    },
    "SDET": {
        "title": "SDET (Software Development Engineer in Test)",
        "category": "Quality & Testing",
        "required_skills": ["Java / Python / TypeScript", "Automation Framework Architecture (Selenium / Playwright / Cypress)", "API Automation (RestAssured / PyTest)", "Data Structures & Coding Basics", "CI/CD Integration", "Git"],
        "preferred_skills": ["Dockerized Test Execution", "Performance Testing (JMeter / Locust)", "BDD Frameworks (Cucumber / Behave)", "SQL & Database Validation"],
        "nice_to_have": ["Mobile Automation (Appium)", "Chaos Engineering", "Mocking & Service Virtualization"],
        "expected_projects": ["Scalable Parallel Test Automation Framework", "CI/CD Integrated API Testing Pipeline", "Visual Regression & Accessibility Testing Suite", "Custom Test Metrics & Reporting Dashboard"],
        "expected_experience_level": "2-5 Years",
        "expected_technologies": ["Python", "Java", "Playwright", "Selenium", "PyTest", "Docker", "GitHub Actions", "PostgreSQL"],
        "ats_keywords": ["sdet", "test automation", "framework development", "selenium", "playwright", "api automation", "ci/cd", "object-oriented programming"],
    },
    "Product Manager": {
        "title": "Product Manager",
        "category": "Product & Business",
        "required_skills": ["Product Lifecycle Management", "User Story Mapping & PRD Writing", "Product Analytics (Mixpanel / Google Analytics)", "Agile / Scrum Methodology", "Wireframing & Specifying Features", "Prioritization Frameworks (RICE / MoSCoW)", "User Research"],
        "preferred_skills": ["SQL for Data Analysis", "A/B Testing Design", "Roadmapping Tools (Linear / Jira / Productboard)", "Technical Understanding of APIs"],
        "nice_to_have": ["Growth Hacking", "Monetization & Pricing Strategy", "CSPO Certification"],
        "expected_projects": ["End-to-End Product Launch Case Study", "User Onboarding Funnel Optimization Project", "Data-Driven Feature Deprecation & Migration Plan", "Competitive Market Analysis & Product Strategy"],
        "expected_experience_level": "2-5 Years",
        "expected_technologies": ["Jira", "Linear", "Mixpanel", "Figma", "SQL", "Notion", "Google Analytics"],
        "ats_keywords": ["product manager", "prd", "user stories", "roadmap", "agile", "scrum", "product analytics", "a/b testing", "feature prioritization"],
    },
    "Business Analyst": {
        "title": "Business Analyst",
        "category": "Product & Business",
        "required_skills": ["Requirements Gathering & BRD / FRD Creation", "Business Process Modeling (BPMN)", "SQL Queries & Data Extraction", "Data Visualization (PowerBI / Tableau / Excel)", "Stakeholder Communication", "Agile / Scrum"],
        "preferred_skills": ["Python for Data Manipulation", "Gap Analysis", "Financial Modeling Basics", "UML Diagramming"],
        "nice_to_have": ["CBAP Certification", "Salesforce / SAP Exposure", "Jira Administration"],
        "expected_projects": ["Enterprise Process Automation Gap Analysis", "Customer Churn Business Requirements Document", "Executive PowerBI Dashboard for Revenue Metrics", "Vendor Evaluation & Selection Matrix"],
        "expected_experience_level": "2-4 Years",
        "expected_technologies": ["SQL", "Excel", "PowerBI", "Tableau", "Jira", "Visio", "Python"],
        "ats_keywords": ["business analyst", "brd", "requirements gathering", "sql", "bpmn", "data analysis", "tableau", "powerbi", "stakeholder management"],
    },
    "UI UX Designer": {
        "title": "UI UX Designer",
        "category": "Design",
        "required_skills": ["Figma / Sketch / Adobe XD", "User Research & Usability Testing", "Wireframing & Prototyping", "Design Systems & Component Libraries", "Visual Design & Typography", "Information Architecture", "Micro-interactions"],
        "preferred_skills": ["Design Tokens & Developer Handoff", "Accessibility Standards (WCAG)", "HTML/CSS Basics", "Motion Design (Lottie/Framer)"],
        "nice_to_have": ["Framer / Webflow Development", "3D Design (Spline/Blender)", "Behavioral Psychology"],
        "expected_projects": ["Comprehensive Design System with Dark/Light Tokens", "Mobile Banking App End-to-End Redesign Case Study", "SaaS B2B Dashboard UI/UX Case Study", "Interactive High-Fidelity Prototype with Micro-animations"],
        "expected_experience_level": "2-4 Years",
        "expected_technologies": ["Figma", "Framer", "Lottie", "Adobe CC", "Miro", "Storybook"],
        "ats_keywords": ["ui ux designer", "figma", "prototyping", "wireframing", "user research", "design system", "information architecture", "user testing"],
    },
    "System Engineer": {
        "title": "System Engineer",
        "category": "Infrastructure",
        "required_skills": ["Linux / Windows Administration", "Networking Protocols (TCP/IP, DNS, DHCP, VPN)", "Shell Scripting (Bash / PowerShell)", "Virtualization (VMware / KVM / Hyper-V)", "Hardware & Server Provisioning", "Git"],
        "preferred_skills": ["Configuration Management (Ansible / Chef)", "Active Directory & LDAP", "Monitoring (Nagios / Zabbix / Prometheus)", "Cloud Infrastructure"],
        "nice_to_have": ["RHCE Certification", "Storage Management (SAN/NAS)", "Backup & Disaster Recovery Planning"],
        "expected_projects": ["Enterprise High-Availability Linux Server Cluster", "Automated Ansible Infrastructure Provisioning", "Active Directory & Single Sign-On Architecture", "Disaster Recovery Automation & Simulation"],
        "expected_experience_level": "2-5 Years",
        "expected_technologies": ["Linux", "Bash", "PowerShell", "VMware", "Ansible", "Nginx", "Zabbix"],
        "ats_keywords": ["systems engineer", "linux administration", "networking", "bash scripting", "virtualization", "ansible", "server infrastructure"],
    },
    "Embedded Engineer": {
        "title": "Embedded Engineer",
        "category": "Hardware & Embedded",
        "required_skills": ["C / C++", "Microcontrollers (STM32, ESP32, AVR, ARM Cortex)", "Hardware Protocols (UART, SPI, I2C, CAN)", "RTOS (FreeRTOS)", "Oscilloscopes & Logic Analyzers", "Git"],
        "preferred_skills": ["Embedded Linux (Yocto)", "PCB Design & Schematic Reading (KiCAD / Altium)", "Low Power Optimization", "Device Drivers"],
        "nice_to_have": ["IoT Security & MQTT", "Bluetooth Low Energy (BLE)", "Rust for Embedded"],
        "expected_projects": ["FreeRTOS Based Multi-Sensor IoT Telemetry Node", "STM32 CAN Bus Vehicle Diagnostic Reader", "Custom KiCAD PCB with ESP32 & Sensors", "Low-Power Firmware with Sleep States & Flash Storage"],
        "expected_experience_level": "2-5 Years",
        "expected_technologies": ["C", "C++", "FreeRTOS", "STM32CubeIDE", "KiCAD", "GDB", "Git"],
        "ats_keywords": ["embedded engineer", "c", "c++", "microcontroller", "rtos", "freertos", "i2c", "spi", "firmware"],
    },
    "Data Engineer": {
        "title": "Data Engineer",
        "category": "AI & Data",
        "required_skills": ["Python / Scala", "Advanced SQL & Database Tuning", "Data Warehousing (Snowflake / BigQuery / Redshift)", "ETL / ELT Pipeline Architecture", "Distributed Data (Apache Spark / PySpark)", "Orchestration (Apache Airflow / Dagster)", "Git"],
        "preferred_skills": ["Data Modeling (Dimensional / Star Schema)", "dbt (data build tool)", "Kafka / Streaming Data", "Docker & Kubernetes"],
        "nice_to_have": ["Delta Lake / Apache Iceberg", "Terraform", "Presto / Trino"],
        "expected_projects": ["Real-Time Streaming Analytics Pipeline with Kafka & Spark", "Enterprise Snowflake Data Warehouse with dbt Models", "Automated Airflow ETL Orchestration Engine", "Data Lakehouse Migration Case Study"],
        "expected_experience_level": "2-5 Years",
        "expected_technologies": ["Python", "SQL", "Spark", "Airflow", "Snowflake", "dbt", "Kafka", "Docker"],
        "ats_keywords": ["data engineer", "etl pipeline", "apache spark", "airflow", "sql", "data warehouse", "snowflake", "data modeling"],
    },
    "Blockchain Developer": {
        "title": "Blockchain Developer",
        "category": "Core Engineering",
        "required_skills": ["Solidity / Rust", "Smart Contract Development & Security", "EVM / Ethereum / Solana Architecture", "Web3.js / Ethers.js / Viem", "Hardhat / Foundry / Anchor", "REST APIs & WebSockets", "Git"],
        "preferred_skills": ["DeFi Protocols & AMM Math", "Smart Contract Auditing & Slither", "IPFS / Arweave Decentralized Storage", "TypeScript"],
        "nice_to_have": ["Zero Knowledge Proofs (zk-SNARKs)", "Layer 2 Rollups", "Cross-Chain Bridges"],
        "expected_projects": ["Audited Decentralized Staking Vault Protocol", "NFT Marketplace Smart Contracts with ERC-721A", "Solana Anchor Based Orderbook Protocol", "Web3 Decentralized Governance DAO Portal"],
        "expected_experience_level": "2-4 Years",
        "expected_technologies": ["Solidity", "TypeScript", "Ethers.js", "Hardhat", "Foundry", "Rust", "Web3"],
        "ats_keywords": ["blockchain developer", "smart contracts", "solidity", "web3", "ethers.js", "hardhat", "evm", "decentralized applications"],
    },
    "Game Developer": {
        "title": "Game Developer",
        "category": "Core Engineering",
        "required_skills": ["C++ / C#", "Unreal Engine / Unity Engine", "Game Physics & Mathematics (Linear Algebra, Vectors)", "Object Pool & Performance Optimization", "Shader Programming (HLSL / GLSL)", "Git / Perforce"],
        "preferred_skills": ["Multiplayer Game Networking (Mirror / Photon / Unreal Dedicated)", "AI & Pathfinding (NavMesh / Behavior Trees)", "Graphics Pipelines", "Profiling Tools"],
        "nice_to_have": ["VR / AR Development", "Custom Engine Mechanics", "Render Graph Architecture"],
        "expected_projects": ["3D Action RPG Mechanics Framework in Unreal Engine 5", "Multiplayer Fast-Paced Shooter System in Unity", "Procedural Dungeon Generation System", "Custom Compute Shader Weather Simulation"],
        "expected_experience_level": "2-5 Years",
        "expected_technologies": ["C++", "C#", "Unreal Engine", "Unity", "HLSL", "Git", "Visual Studio"],
        "ats_keywords": ["game developer", "unity", "unreal engine", "c++", "c#", "game physics", "gameplay programming", "multiplayer"],
    }
}


def get_role_list() -> List[Dict[str, str]]:
    """Returns simplified list of roles for UI selection."""
    return [
        {
            "id": key,
            "title": val["title"],
            "category": val["category"],
            "expected_experience": val["expected_experience_level"]
        }
        for key, val in ROLES_DATABASE.items()
    ]


def get_role_profile(role_name: str) -> Dict[str, Any]:
    """Returns detailed hiring profile for given role or fallback Software Engineer profile."""
    if role_name in ROLES_DATABASE:
        return ROLES_DATABASE[role_name]
    
    # Fuzzy match or fallback
    for key, val in ROLES_DATABASE.items():
        if role_name.lower() in key.lower():
            return val
            
    return ROLES_DATABASE["Software Engineer"]
